# Generated by Django 4.2.26 on 2026-02-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeprofile',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='salary',
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
