# Generated by Django 4.2.26 on 2026-02-13 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employeeprofile_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeSalary',
        ),
    ]
