# Generated by Django 4.2.26 on 2026-02-10 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('systemcontrol', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-created_at'], 'verbose_name': 'Announcement', 'verbose_name_plural': 'Announcements'},
        ),
        migrations.AlterModelOptions(
            name='systemsetting',
            options={'verbose_name': 'System Setting', 'verbose_name_plural': 'System Settings'},
        ),
        migrations.AlterModelOptions(
            name='userloginactivity',
            options={'ordering': ['-logged_in_at'], 'verbose_name': 'User Login Activity', 'verbose_name_plural': 'User Login Activities'},
        ),
        migrations.AddField(
            model_name='announcement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Admin user who created this announcement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this announcement is currently active'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='message',
            field=models.TextField(help_text='Announcement message content'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(help_text='Announcement title', max_length=200),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='capacity_per_class',
            field=models.PositiveIntegerField(default=30, help_text='Maximum capacity per class'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='current_academic_year',
            field=models.CharField(default='2026-2027', help_text='Current academic year (e.g., 2026-2027)', max_length=20),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='enable_notifications',
            field=models.BooleanField(default=True, help_text='Enable/disable system notifications'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='school_class_name',
            field=models.CharField(default='Royal Public School', help_text='Official name of the school', max_length=100),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['-created_at'], name='systemcontr_created_66dac5_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['is_active', '-created_at'], name='systemcontr_is_acti_811aaa_idx'),
        ),
        migrations.AddIndex(
            model_name='userloginactivity',
            index=models.Index(fields=['-logged_in_at'], name='systemcontr_logged__bc0dad_idx'),
        ),
    ]
