# Generated by Django 4.2.26 on 2026-02-10 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employeeprofile_options_and_more'),
        ('teachers', '0003_alter_teacherprofile_subject'),
        ('schoolclassesmanage', '0001_initial'),
        ('students', '0004_assignment_assignmentsubmission_submissionattachment_and_more'),
        ('attendence', '0004_remove_leave_additional_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('sick', 'Sick'), ('personal', 'Personal'), ('emergency', 'Emergency'), ('vacation', 'Vacation'), ('other', 'Other')], max_length=20)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('reason', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='employees.employeeprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('sick', 'Sick'), ('personal', 'Personal'), ('emergency', 'Emergency'), ('vacation', 'Vacation'), ('other', 'Other')], max_length=20)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('reason', models.TextField()),
                ('approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='teachers.teacherprofile')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='studentattendance',
            unique_together={('student', 'school_class', 'date')},
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late'), ('Half Day', 'Half Day'), ('On Leave', 'On Leave')], max_length=15),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late'), ('Half Day', 'Half Day'), ('On Leave', 'On Leave')], max_length=15),
        ),
        migrations.AlterField(
            model_name='teacherattendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late'), ('Half Day', 'Half Day'), ('On Leave', 'On Leave')], max_length=15),
        ),
        migrations.DeleteModel(
            name='Leave',
        ),
        migrations.RemoveField(
            model_name='studentattendance',
            name='marked_by',
        ),
    ]
