# Generated by Django 4.2.26 on 2026-02-03 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.CharField(choices=[('All Students', 'All Students'), ('All Teachers', 'All Teachers'), ('All Parents', 'All Parents'), ('Class 10', 'Class 10'), ('Class 9', 'Class 9'), ('Class 8', 'Class 8'), ('Class 7', 'Class 7'), ('Class 6', 'Class 6'), ('Class 5', 'Class 5'), ('Class 4', 'Class 4'), ('Class 3', 'Class 3'), ('Class 2', 'Class 2'), ('Class 1', 'Class 1'), ('UKG', 'UKG'), ('LKG', 'LKG'), ('Nursery', 'Nursery'), ('Specific Students', 'Specific Students'), ('Specific Teachers', 'Specific Teachers'), ('Specific Parents', 'Specific Parents')], max_length=50),
        ),
    ]
