# Generated by Django 4.2.26 on 2026-02-13 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_alter_teacherprofile_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherSalary',
        ),
    ]
