# Generated by Django 4.2.26 on 2026-01-30 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0003_initial'),
        ('schoolclassesmanage', '0001_initial'),
        ('exams', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexam',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentexam',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolclassesmanage.schoolclass'),
        ),
        migrations.AddField(
            model_name='studentexam',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examresult',
            name='class_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='schoolclassesmanage.schoolclass'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='students.studentprofile'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='exam',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='schoolclassesmanage.schoolclass'),
        ),
        migrations.AddField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academics.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='examresult',
            unique_together={('exam', 'subject', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('exam_type', 'subject', 'school_class')},
        ),
    ]
