# Generated by Django 4.2.26 on 2026-02-18 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_alter_subject_assigned_classes'),
        ('students', '0004_assignment_assignmentsubmission_submissionattachment_and_more'),
        ('exams', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('grade', models.CharField(blank=True, max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='studentexam',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='studentexam',
            name='school_class',
        ),
        migrations.RemoveField(
            model_name='studentexam',
            name='updated_by',
        ),
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='exam',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('Unit Test', 'Unit Test'), ('Midterm', 'Midterm'), ('Final', 'Final'), ('Quarterly', 'Quarterly')], max_length=50),
        ),
        migrations.DeleteModel(
            name='ExamResult',
        ),
        migrations.DeleteModel(
            name='StudentExam',
        ),
        migrations.AddField(
            model_name='studentexamresult',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='exams.exam'),
        ),
        migrations.AddField(
            model_name='studentexamresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='students.studentprofile'),
        ),
        migrations.AddField(
            model_name='studentexamresult',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject'),
        ),
        migrations.RemoveField(
            model_name='exam',
            name='max_marks',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='subject',
        ),
        migrations.AlterUniqueTogether(
            name='studentexamresult',
            unique_together={('student', 'exam', 'subject')},
        ),
    ]
