# Generated by Django 4.2.26 on 2026-01-30 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schoolclassesmanage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_name', models.CharField(max_length=100, unique=True)),
                ('house_color', models.CharField(max_length=20)),
                ('house_captain', models.CharField(blank=True, max_length=100, null=True)),
                ('vice_captain', models.CharField(blank=True, max_length=100, null=True)),
                ('house_motto', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SportsGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('sport_type', models.CharField(choices=[('Football', 'Football'), ('Basketball', 'Basketball'), ('Cricket', 'Cricket'), ('Tennis', 'Tennis'), ('Swimming', 'Swimming'), ('Athletics', 'Athletics'), ('Badminton', 'Badminton'), ('Volleyball', 'Volleyball'), ('Hockey', 'Hockey'), ('Table Tennis', 'Table Tennis'), ('Baseball', 'Baseball'), ('Rugby', 'Rugby'), ('Wrestling', 'Wrestling')], max_length=50)),
                ('coach_name', models.CharField(max_length=100)),
                ('max_members', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('credits', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectClassAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='schoolclassesmanage.schoolclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_assignments', to='academics.subject')),
            ],
            options={
                'verbose_name': 'Subject Class Assignment',
                'verbose_name_plural': 'Subject Class Assignments',
            },
        ),
    ]
