# Generated by Django 4.2.26 on 2026-01-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='assigned_classes',
            field=models.ManyToManyField(blank=True, related_name='subjects', to='facilities.classroom'),
        ),
    ]
