# Generated by Django 4.2.26 on 2026-01-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='teaching_subjects', to='teachers.teacherprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='sportsgroup',
            unique_together={('group_name', 'sport_type')},
        ),
        migrations.AlterUniqueTogether(
            name='subjectclassassignment',
            unique_together={('subject', 'school_class')},
        ),
    ]
