# Generated by Django 4.2.26 on 2026-02-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='teachers',
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
