# Generated by Django 4.2.26 on 2026-02-09 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_remove_subject_teachers_alter_subject_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubjectClassAssignment',
        ),
    ]
