# Generated by Django 4.2.26 on 2026-01-30 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schoolclassesmanage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('nationality', models.CharField(max_length=50)),
                ('aadhaar_number', models.CharField(max_length=12)),
                ('category', models.CharField(choices=[('GEN', 'General'), ('SC', 'Scheduled Caste'), ('ST', 'Scheduled Tribe'), ('OBC', 'Other Backward Class'), ('EWS', 'Economically Weaker Section')], max_length=10)),
                ('academic_year', models.CharField(max_length=9)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Approved', max_length=20)),
                ('admission_date', models.DateField(null=True)),
                ('student_type', models.CharField(choices=[('New', 'New'), ('Transfer', 'Transfer')], max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('father_name', models.CharField(max_length=100)),
                ('father_occupation', models.CharField(blank=True, max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('mother_occupation', models.CharField(blank=True, max_length=100)),
                ('guardian_name', models.CharField(blank=True, max_length=100)),
                ('guardian_relationship', models.CharField(blank=True, max_length=50)),
                ('guardian_contact', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('alternate_number', models.CharField(blank=True, max_length=15)),
                ('photo', models.FileField(upload_to='admissions/photos/')),
                ('signature', models.FileField(upload_to='admissions/signatures/')),
                ('birth_certificate', models.FileField(upload_to='admissions/birth_certificates/')),
                ('aadhaar_card', models.FileField(upload_to='admissions/id_proofs/')),
                ('transfer_certificate', models.FileField(blank=True, null=True, upload_to='admissions/tc/')),
                ('previous_report', models.FileField(blank=True, null=True, upload_to='admissions/reports/')),
                ('caste_certificate', models.FileField(blank=True, null=True, upload_to='admissions/caste/')),
                ('medical_certificate', models.FileField(blank=True, null=True, upload_to='admissions/medical/')),
                ('is_paid', models.BooleanField(default=False)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('class_applied', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admission_applications', to='schoolclassesmanage.schoolclass')),
            ],
        ),
    ]
